version: '3'

services:
  influxdb:
    image: influxdb:2.7-alpine
    container_name: iflux
    env_file:
      - influxv2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
  telegraf:
    image: telegraf:1.28-alpine
    container_name: tg
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf/telegraf-common.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/telegraf.d:/etc/telegraf/telegraf.d:ro
      - ./telegraf/lookup.csv:/etc/telegraf/lookup.csv:ro
    env_file:
      - influxv2.env

volumes:
  influxdbv2: